---

name: Build and push container image
# yamllint disable rule:truthy
on:
  push:
    branches:
      - main
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ vars.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          # based on if we are on a tag or not
          # set the image tag to latest or the tag
          tags: |
            ${{ github.repository_owner }}/jupyter:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/jupyter:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
            quay.io/${{ github.repository_owner }}/jupyter:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
