---
name: Package
# yamllint disable rule:truthy
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  package_waldiez_jupyter:
    runs-on: ubuntu-latest
    name: Package Python 🐍 distribution 📦
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install corepack and yarn
        run: |
          corepack enable
          yarn set version stable

      - name: Install dependencies
        run: |
          yarn install
          python -m pip install --break-system-packages jupyterlab build twine

      - name: Build package 🏗️
        run: |
          yarn cache clean
          yarn install
          yarn build
          python scripts/build.py

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: waldiez-jupyter
          path: dist/*

  publish_waldiez_jupyter:
    runs-on: ubuntu-latest
    needs: package_waldiez_jupyter
    name: Publish Python 🐍 distribution 📦
    environment:
      name: pypi
      url: https://pypi.org/p/waldiez-jupyter
    steps:
      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: waldiez-jupyter
          path: dist

      - name: Upload to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist

      - name: List generated files
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Generated files:"
          ls -la dist
